Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,25 +16,32 @@ jobs:
             -Dsonar.projectKey=Dvir-Segal_harmony-endpoint-management-py-sdk
             -Dsonar.branch.name=release
 
-      - name: Fail build if high severity issues exist
-        run: |
-          # Make the API request and get the result
-          result=$(curl -s -u "token:${{ secrets.SONAR_TOKEN }}" \
-            "https://sonarcloud.io/api/issues/search?componentKeys=Dvir-Segal_harmony-endpoint-management-py-sdk&severities=CRITICAL,MAJOR")
+      - name: Check SonarCloud Quality Gate (Fail on High Severity)
+        uses: gr2m/sonarcloud-quality-gate@v2
+        with:
+          organization: dvir-segal
+          project_key: Dvir-Segal_harmony-endpoint-management-py-sdk
+          condition: severity >= 'BLOCKER'
 
-          # Output the result to help with debugging
-          echo "SonarCloud API response: $result"
+      # - name: Fail build if high severity issues exist
+      #   run: |
+      #     # Make the API request and get the result
+      #     result=$(curl -s -u "token:${{ secrets.SONAR_TOKEN }}" \
+      #       "https://sonarcloud.io/api/issues/search?componentKeys=Dvir-Segal_harmony-endpoint-management-py-sdk&severities=CRITICAL,MAJOR")
 
-          # Extract the total number of issues
-          total_issues=$(echo "$result" | jq '.paging.total')
+      #     # Output the result to help with debugging
+      #     echo "SonarCloud API response: $result"
 
-          # Fail the build if there are any critical or major issues
-          if [ "$total_issues" -gt 0 ]; then
-            echo "Build failed: There are $total_issues high severity issues (Critical or Major).";
-            exit 1
-          else
-            echo "No high severity issues found. Continuing build.";
-          fi
+      #     # Extract the total number of issues
+      #     total_issues=$(echo "$result" | jq '.paging.total')
+
+      #     # Fail the build if there are any critical or major issues
+      #     if [ "$total_issues" -gt 0 ]; then
+      #       echo "Build failed: There are $total_issues high severity issues (Critical or Major).";
+      #       exit 1
+      #     else
+      #       echo "No high severity issues found. Continuing build.";
+      #     fi
       #   uses: snyk/actions/python@master
       #   continue-on-error: true # To make sure that SARIF upload gets called
       #   env:
